### ISSUE TITLE
输入法按回车键怎么变成英文字母

### ISSUE THREAD

**Issue by danerlt** [yanhuacuo/98wubi-tables#12]
类似于其他输入法,敲完键盘后按回车显示成英文，比如按键盘：n i h  a o 之后按回车，结果是：nihao

**Comment by danerlt** [comment]
![image](https://user-images.githubusercontent.com/14197717/201527360-a94acf27-8dee-4365-844f-19de28d9023d.png)

**Comment by yanhuacuo** [comment]
在你找到的这个界面，有「候选上屏」，其中应有「所输入的编码上屏」，是这样吗？

**Comment by danerlt** [comment]
@yanhuacuo 已解决，如图：
![image](https://user-images.githubusercontent.com/14197717/206095393-a1f9d073-59ab-4e18-8c0e-67423f972106.png)
