### ISSUE TITLE
加字 𦮼 不生效

### ISSUE THREAD

**Issue by drcxd** [yanhuacuo/98wubi-tables#13]
我在 wubi98_ci_extended.dict.yaml 的末尾加了一行
```
𦮼 ffnn
```
但重新部署之后 ffnn 并没有列出这个字。用rimetool GUI 的无码加词功能添加这个字会导致 GUI 程序崩溃。
该如何添加这个字？

**Comment by yanhuacuo** [comment]
这个字，在「超集」码表中，可以打出来。『rimetool』面向一般功能和通用码表管理设计，没有为超集字设计处理间空，所以暂不可处理超集字。

如果需要加字，最好「仿写」已有码表，不要手动打，因为码表的「间隔符」是「tab」（YAML语法规定的），很多文本编辑器不支持「tab」键直出。

**Comment by drcxd** [comment]
那么我该如何才能打出「超集」码表中的字？安装超集字体就可以吗？

**Comment by yanhuacuo** [comment]
> 那么我该如何才能打出「超集」码表中的字？安装超集字体就可以吗？

是的，资源库里有「字体」目录，你找一下。

**Comment by yanhuacuo** [comment]
> 那么我该如何才能打出「超集」码表中的字？安装超集字体就可以吗？

ctrl+~ 可以临时切换到「超集码表中」。
