### ISSUE TITLE
大佬，我要输入带音调的拼音要怎么办？望给个提示，谢谢大佬

### ISSUE THREAD

**Issue by jingjingxyk** [yanhuacuo/98wubi-tables#16]
我找到了

symbols.yaml  文件所在地址：  https://github.com/yanhuacuo/98wubi/blob/master/symbols.yaml

所在仓库https://github.com/yanhuacuo/98wubi

**Comment by yanhuacuo** [comment]
一般是「/」+ 某个键。

**Comment by jingjingxyk** [comment]
找到码表，拼音映射： https://github.com/yanhuacuo/98wubi/blob/6338b349d5ccdb7d9a47b3dcbf16e2ed11bc3bfa/symbols.yaml#L279

输入 `[/py] ` 选择需要的拼音符号即可
```text
/py

````
