### ISSUE TITLE
求 fcitx 主题与字体

### ISSUE THREAD

**Issue by amosbird** [yanhuacuo/98wubi-tables#2]
这个主题和字体太赞啦，https://raw.githubusercontent.com/yanhuacuo/98wubi/master/linux/%E5%B0%8F%E7%8B%BC%E6%AF%AB.gif

能分享一下吗？ linux能用吗？谢谢

**Comment by yanhuacuo** [comment]
不属于 fcitx

**Comment by yanhuacuo** [comment]
fcitx5 上，已实现相关功能

https://github.com/yanhuacuo/rime98wb
