### ISSUE TITLE
小狼毫0702版本无法切换界面风格

### ISSUE THREAD

**Issue by drcxd** [yanhuacuo/98wubi-tables#20]
你好，我不知道是不是应该在这里提这个问题，但这里是我找得到的最有可能得到回复的地方。

如题，我在98五笔资源库中下载的2023/7/2上传的小狼毫最新版，安装成功后无法通过右击托盘中的图标->输入法设定->方案选单设定->界面风格设定来修改界面风格。

重新安装也不能解决这个问题。输入的功能是正常的。

不知该如何解决该问题？

**Comment by yanhuacuo** [comment]
请使用「98五笔资源库」发布的 weasel-tool 来切换主题，这个并非是个 bug。

新版的 weasel 接受「方案补丁」里的配色方案，这个特性很好，这可以使我们在「单字」与「含词」等不同选单下，使用最恰当的配色与排版风格。

weasel 的设置入口，会把配色信息写到「weasel.custom.yaml」中，但是它的权级，是低于「wubi98_ci.custom.yaml」或同属性的方案补丁的。

weasel 那个设置程序没有出错，它一如继往写到「weasel.custom.yaml」，但是已经被「wubi98_ci.custom.yaml」等方案补丁优先了。

你可以在  [这里](https://github.com/yanhuacuo/98wubi-tables/blob/master/%E8%BE%93%E5%85%A5%E6%B3%95%E8%BD%AF%E4%BB%B6/weasel-tool.7z) 或资源库里，用 「weasel-tool.7z」这个工具，来改主题。


![pic](https://raw.githubusercontent.com/yanhuacuo/Demo_PIC/main/weasel-tool-shot/3.png)
