### ISSUE TITLE
你好，3个辅助工具的全局热键可以禁用吗？

### ISSUE THREAD

**Issue by darklonely** [yanhuacuo/98wubi-tables#21]
你好，安装后发现3个辅助工具分别占用了：ctrl+alt+q，ctrl+alt+w，ctrl+alt+e全局热键，请问有设置或方法禁用吗？
这3个热键是本人常用的热键，被占用后，总是提示冲突，操作不方便。

**Comment by yanhuacuo** [comment]
打开:

 `C:\ProgramData\Microsoft\Windows\Start Menu\Programs\小狼毫输入法`

快捷方式这里，右键，查看「属性」

「快捷键」一栏，按「Delete」，使之成「无」，确认之。

**Comment by yanhuacuo** [comment]
下次更新，这三个热键就解除掉它。
本属试验性质，带来困扰，深表抱歉。
