### ISSUE TITLE
请问是否有全字根表？

### ISSUE THREAD

**Issue by fir05** [yanhuacuo/98wubi-tables#24]
不好意思，我想对规则进行一些微调，比如把鳄的鱼字头和"一"划分为鱼，那么键位就从 "qgkn" 变成了 "qkn"，但丢失了k和n 之间的 "口 二"，也无法保持4键位。我只好放弃了修改。
请问这个库有全字根表吗？或者说当前的工具有办法获取吗？谢谢。

**Comment by yanhuacuo** [comment]
这种第一手的信息，对于98五笔这种成熟的、发布已久的成品形码，是不可能存在的。
