### ISSUE TITLE
你好，请问提到的拆分数据在哪里可以访问呢

### ISSUE THREAD

**Issue by Newdea** [yanhuacuo/98wubi-tables#28]
看到[说明](https://github.com/yanhuacuo/98wubi-tables/tree/master/98%E4%BA%94%E7%AC%94%E6%8B%86%E5%88%86%E6%98%A0%E5%B0%84%E8%A1%A8#readme) 中说是用到了拆分数据，我目前在找这样的数据，想根据拆分自己魔改份五笔方案，如果可以分享，希望能提供下出处，谢谢。

**Comment by yanhuacuo** [comment]
https://github.com/yanhuacuo/98wubi-unicode/tree/master/python-Unicode/CJK
