### ISSUE TITLE
屌  这个字挺常用的，但不属于gb2312，怎么把它移到gb2312里，谢谢

### ISSUE THREAD

**Issue by Dreamray** [yanhuacuo/98wubi-tables#29]
比如屌爆了就经常用

**Comment by yanhuacuo** [comment]
其实也说明 gb2312 已经过于落伍了。
这个改不了啊，现在已经不提供 gb2312 表了。

**Comment by Dreamray** [comment]
> 其实也说明 gb2312 已经过于落伍了。 这个改不了啊，现在已经不提供 gb2312 表了。

那怎么把它移到常用字库里啊（就是ctrl+shift+u快捷键切换的那个），我不想用扩展字库（重码多，太多字用不着）
