### ISSUE TITLE
多重翻译器与候选备注冲突

### ISSUE THREAD

**Issue by linzianxyz** [yanhuacuo/98wubi-tables#30]
**描述遇到的问题**
前提一：自用的五笔输入方案，功能：
1.固态词典里的字和词固顶，且排在候选前列。这一功能需要关闭用户词典。
2.开启造词功能，即开启太极图标，并将自造词存进一个新词典（wubi98.txt）内。这一功能需要启用用户词典。
在借鉴98五笔的相关配置，利用三重翻译器成功实现这一看似是无解的难题，即固顶和自造词不能同时生效的
前提二：
rime启用反查功能（reverse_up），启用目的是，对于非常用字无法准确识记编码，实现以Z键引导拼音， 反查该字的正确编码，实质是知音查形。
前提三：
启用备注功能（reverse_up）。启用目的是，对于某一字的编码，用户已经形成条反，但是用户不能准确掌握该字的读音，出现“这个字我会打，但是我不知道该字的正确读音”的情况。如，汉字“拔和拨”。因而利用备注功能实现将候选字的正确拼音标出并紧随候选字后，用户就能知晓该字的正确拼音，从而避免错出的尴尬。这一功能实质是知形查音。
**复现步骤**
重现问题的步骤，如：
输入过程发现rime能正常实现备注功能。但是，当Z键引导拼音反查时，输入该字的第一个声母，rime反查列出所有以该声母开头的字的编码。如输入w，列出王､完､吾､味等等，所有字的正确编码。但是当输入完整编码时，反而列出的是该字的拼音。也即用户希望知音查形，结果却是知音查音，违背用户以音查形的初衷！

**预期行为**
希望在不影响前提一的情况下，正常实现反查功能。

**用户文件**
请于此附上 weasel 用户文件夹下的内容，方便开发者调试问题

**截图**

https://github.com/yanhuacuo/98wubi-tables/assets/15376679/95cbed8d-0f43-434c-aeb5-2cda06a9904b

**其他补充说明**
无

**Comment by linzianxyz** [comment]
[Uploading rime.zip…]()

**Comment by yanhuacuo** [comment]
lua 组件协作下，没有问题。

**Comment by linzianxyz** [comment]
> lua 组件协作下，没有问题。

看来这个问题只能借助lua。但是就是想的是能尽量不动，内部实现。
