### ISSUE TITLE
https://98wb.github.io/ 404，Mac package 建议加上数字签名，另恳请作者提供 homebrew 的打包方案

### ISSUE THREAD

**Issue by ge-xin** [yanhuacuo/98wubi-tables#4]
此外可能我找得不细，拆字少字体的链接 orz

**Comment by yanhuacuo** [comment]
为了访问速度，网站已全部转向国内托管：https://wubi98.gitee.io/

Mac package 数字签名？这个不太清楚，不是我打的包。

不过，资源库里提供 shell 脚本的增量更新：

『已装过鼠须管的同学——可以使用mac增量更新，双击一下就完成更新。』

http://98wb.ys168.com/

**Comment by ge-xin** [comment]
Yes I found this https://github.com/98wb/mac which is really helpful.

Basically old way of packaging in this repo breaks the signature. So macOS complains because it is not the same as the original author's binary.

So I would suggest the best way, if Mac user use Homebrew for package management is (thanks for your new repo, I also found this one)

```
brew cask install squirrel && sh -c "$(curl -fsSL https://gitee.com/wubi98/shell/raw/master/98wb.sh)"

```

Homebrew is a popular package management tool similar to Linux's apt-get, the official site is https://brew.sh/

In that way macOS won't complain the digital signature, because we are overriding the user settings in RIME's official release, not breaking the original package.

Thank you very much! Feel free to add my homebrew command if you want!

**Comment by ge-xin** [comment]
然后鼠须管的只有单字模式吗。。

**Comment by yanhuacuo** [comment]
好的

**Comment by yanhuacuo** [comment]
https://developer.apple.com/cn/developer-id/

https://www.cnblogs.com/wx1993/p/13277678.html

**Comment by yanhuacuo** [comment]
考虑到签名的「成本问题」，现在有了更好的解决方案：


https://github.com/yanhuacuo/98wubi-tables/blob/master/%E8%BE%93%E5%85%A5%E6%B3%95%E8%BD%AF%E4%BB%B6/%E6%9C%80%E6%96%B0%E7%89%88%E6%9C%AC%E9%BC%A0%E9%A1%BB%E7%AE%A1.zip

**Comment by yanhuacuo** [comment]
后续优化：

https://gitee.com/wubi98/squirrel
