### ISSUE TITLE
您好，请问鼠须管字库，只有单字模式吗

### ISSUE THREAD

**Issue by ge-xin** [yanhuacuo/98wubi-tables#5]
如题，谢谢作者，我比较水，一般是二简和词组一起打的hh，单字也可，就是三码以上有点慢

**Comment by yanhuacuo** [comment]
https://wubi98.gitee.io/2020/04/27/2019-12-03-032.squirrel/#%E5%AE%89%E8%A3%85%E4%B8%8E%E4%BD%BF%E7%94%A8

**Comment by ge-xin** [comment]
谢谢！
