### ISSUE TITLE
MacOS Big Sur 11.2.2 （M1芯片）鼠须管拆分笔画显示为问号

### ISSUE THREAD

**Issue by zhoutengye** [yanhuacuo/98wubi-tables#6]
首先感谢作者的工作。新手，正在学习五笔，看到拆分笔画这个功能十分惊艳，就试了下安装，homebrew和zip都试过了，拆分的笔画显示都是问号，不知道是不是M1的兼容问题

**Comment by yanhuacuo** [comment]
http://98wb.ys168.com/

下载：「4——拆分/超集字体必装字体」

安装下面的所有字体，以便支持十万超集及拆分显示。

另外，鼠须管也更新了，从那里，MacOS 目录下，下载新版。
