### ISSUE TITLE
应该是“再接再厉”，而不是“再接再砺”，建议删除“再接再砺”

### ISSUE THREAD

**Issue by zydxhs** [yanhuacuo/98wubi-tables#8]

**Comment by yanhuacuo** [comment]
https://chengyu.qianp.com/cy/%E5%86%8D%E6%8E%A5%E5%86%8D%E7%A0%BA

**Comment by zydxhs** [comment]
@yanhuacuo 以下两个网站应该比较权威吧，都没有收录 ”再接再砺“：

- [大辞海](http://www.dacihai.com.cn/) 只有“再接再厉”，没有“再接再励。
- [中国华文教育网](http://www.hwjyw.com/resource/content/2015/06/16/31716.shtml) 的解释：

对“再接再厉”这个成语的误用，主要表现在把“厉”误写为“励”。如果用嘴说这个成语显现不出有错误；一写，比如题词，这个错误就显现出来了。许多人把“再接再厉”的“厉”写成“励”，是觉得“励”是“勉励”，把“再接再励”理解为“再接着努力，再一次地勉励自己”。表现上看似乎讲得通，实际上是把这个成语误解了。

　　“再接再厉”语出韩愈、孟郊《斗鸡联句》：“一喷一醒然，再接再厉尔。”此中的“喷”是指在斗鸡时向鸡头上喷水，刺激鸡清醒；“再”是“再一次”；“接”是“接触，接战”；“厉”是“砺”的古字，是磨刀石，在诗中引申为“磨砺”。“磨砺”什么呢？就是斗鸡为了使喙(嘴)更有杀伤力，在接战之前再磨砺喙。“尔”是语气词，表示肯定。把两句诗合起来今译就是：用凉水喷一下正在掐斗的鸡使其清醒鼓舞，再次交锋之前斗鸡要磨嘴使其锋利以利再战。由于“再接再厉”是“再次交锋前磨一磨嘴以利再战”，因此后来就用“再接再厉”比喻一次又一次地努力，奋斗不懈。

**Comment by yanhuacuo** [comment]
> @yanhuacuo 以下两个网站应该比较权威吧，都没有收录 ”再接再砺“：
> 
> * [大辞海](http://www.dacihai.com.cn/) 只有“再接再厉”，没有“再接再励。
> * [中国华文教育网](http://www.hwjyw.com/resource/content/2015/06/16/31716.shtml) 的解释：
> 
> 对“再接再厉”这个成语的误用，主要表现在把“厉”误写为“励”。如果用嘴说这个成语显现不出有错误；一写，比如题词，这个错误就显现出来了。许多人把“再接再厉”的“厉”写成“励”，是觉得“励”是“勉励”，把“再接再励”理解为“再接着努力，再一次地勉励自己”。表现上看似乎讲得通，实际上是把这个成语误解了。
> 
> 　　“再接再厉”语出韩愈、孟郊《斗鸡联句》：“一喷一醒然，再接再厉尔。”此中的“喷”是指在斗鸡时向鸡头上喷水，刺激鸡清醒；“再”是“再一次”；“接”是“接触，接战”；“厉”是“砺”的古字，是磨刀石，在诗中引申为“磨砺”。“磨砺”什么呢？就是斗鸡为了使喙(嘴)更有杀伤力，在接战之前再磨砺喙。“尔”是语气词，表示肯定。把两句诗合起来今译就是：用凉水喷一下正在掐斗的鸡使其清醒鼓舞，再次交锋之前斗鸡要磨嘴使其锋利以利再战。由于“再接再厉”是“再次交锋前磨一磨嘴以利再战”，因此后来就用“再接再厉”比喻一次又一次地努力，奋斗不懈。

```
“厉”是“砺”的古字，是磨刀石，在诗中引申为“磨砺”。“磨砺”什么呢？就是斗鸡为了使喙(嘴)更有杀伤力，在接战之前再磨砺喙。
```
